name: Install Dependencies

on:
  workflow_call:
    inputs:
      python-version:
        required: true
        type: string

jobs:
  install:
    name: Install Dependencies
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up UV Environment
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true
          cache-dependency-glob: uv.lock

      - name: Install Dependencies
        run: uv sync
