version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.13"
  commands:
    - asdf plugin add uv
    - asdf install uv latest
    - asdf global uv latest
    - uv sync --extra docs --frozen
    - mkdir -p $READTHEDOCS_OUTPUT/html/
    - uv run -m sphinx -E -T -a -b html -D language=en docs $READTHEDOCS_OUTPUT/html

# # Build documentation in the "docs/" directory with Sphinx
# sphinx:
#   configuration: docs/conf.py

# # Install dependencies for the documentation
# python:
#   install:
#     - method: pip
#       path: .
#       extra_requirements:
#         - docs
