build:
  os: ubuntu-22.04
  tools:
    python: "3.13"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install dependencies for the documentation
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
