build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py

# Install dependencies for the documentation
python:
  install:
    - requirements: docs/requirements.txt
