name: Reusable Setup

on:
  workflow_call:
    inputs:
      python-version:
        description: 'Python version'
        type: string
        default: '3.13'
      install-groups:
        description: 'Dependency groups to install'
        type: string
        default: 'dev'
      fetch-depth:
        description: 'Number of commits to fetch. 0 indicates all history for all branches and tags'
        type: number
        default: 1
      enable-cache:
        description: 'Enable UV cache'
        type: boolean
        default: true
    outputs:
      python-version:
        description: 'Python version used'
        value: ${{ jobs.setup.outputs.python-version }}

env:
  UV_CACHE_DIR: /tmp/uv-cache
  FORCE_COLOR: "1"

jobs:
  setup:
    runs-on: ubuntu-24.04
    outputs:
      python-version: ${{ steps.output.outputs.python-version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: ${{ inputs.fetch-depth }}

      - name: Setup UV & Python
        uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb # v6
        with:
          enable-cache: ${{ inputs.enable-cache }}
          python-version: ${{ inputs.python-version }}
          cache-dependency-glob: uv.lock

      - name: Install Dependencies
        run: |
          if [[ "${{ inputs.install-groups }}" == "all" ]]; then
            uv sync --all-groups
          else
            uv sync --group=${{ inputs.install-groups }}
          fi

      - name: Set Output
        id: output
        run: echo "python-version=${{ inputs.python-version }}" >> $GITHUB_OUTPUT
