name: Build and Deploy Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build and Push Docker Image to GitHub Container Registry
    needs: cd
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU for Multi-Architecture Builds
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx for Multi-Platform Builds
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker Image Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/mountaingod2/chaturbate_poller
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Log in to GitHub Container Registry
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: '${{ github.repository_owner }}'
          password: '${{ secrets.GITHUB_TOKEN }}'

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v6
        with:
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

      - name: Run Docker Image Tests
        run: docker run --rm ghcr.io/mountaingod2/chaturbate_poller:latest --version
